# Generated by Django 4.0.4 on 2022-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
