# Generated by Django 4.0.4 on 2022-06-07 11:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_author_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(default='Iran', max_length=2),
        ),
    ]
