# Generated by Django 4.0.4 on 2022-05-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_author_birth_date_alter_author_birth_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='author',
        ),
    ]
