# Generated by Django 4.0.3 on 2022-04-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_options_book_date_added_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='digital',
        ),
    ]
