# Generated by Django 4.0.4 on 2022-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
