# Generated by Django 4.0.4 on 2022-05-07 08:47

import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(default=1397, validators=[django.core.validators.MinValueValidator(1984), store.models.max_value_current_year], verbose_name='publish_year'),
            preserve_default=False,
        ),
    ]
