# Generated by Django 4.0.4 on 2022-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book_language_book_translator_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
