# Generated by Django 4.0.4 on 2022-05-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_customer_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
