# Generated by Django 4.0.3 on 2022-05-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_illustrator_book_illustrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Illustrator',
            new_name='illustrator',
        ),
    ]
