# Generated by Django 4.0.4 on 2022-06-03 15:05

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_customer_birth_date_customer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_author),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_book),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_customer),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_illustrator),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.upload_publisher),
        ),
    ]
